- .github/workflows/general.yml
- pg_replicate/Cargo.toml
- pg_replicate/src/clients/mod.rs
- pg_replicate/src/pipeline/sinks/mod.rs
- replicator/Cargo.toml
> Put sinks behind feature flags

- api/src/routes/sinks_pipelines.rs
- api/tests/api/sinks_pipelines.rs
Added a new test in which the `POST sinks-pipelines` is passed the source id from a different tenant. The expected result in this case should be 404, but the code incorrectly accepted the cross-tenant source id. This PR fixes the bug.
> add a new cross tenant pipeline creation test and fixed a bug it exposed

- .gitignore
- api/README.md
- api/scripts/init_db.sh
This PR improves the script for setting up the database, to make it more user friendly. In addition, it also improves the README for the `api` crate.
> feat(script): Improve the script for setting up the database and update README for api

- telemetry/src/lib.rs
Feature
If the API or replicator binaries panic, the panic details are not sent to Logflare.
Whenever there is a panic in the API or replicator binaries, the panic details will be sent to Logflare.
N/A
> send panic logs to Logflare

- .github/workflows/general.yml
- api/tests/common/database.rs
Clippy was not running for tests.
> fix: run cargo clippy for all targets in ci

- README.md
> docs: correct links in readme

- README.md
- api/README.md
- docs/database-setup.md
- docs/etl-design.md
- etl/README.md
- postgres/README.md
- replicator/README.md
- scripts/init_db.sh
- telemetry/README.md
This PR adds new README files for each crate, improves existing READMEs by bringing them up to date with the current development status, and creates a `/docs` folder for shared documentation.
> ref(docs): Improve READMEs

- docs/index.md
This PR adds content to the home page of the documentation site.
> docs: add content to the home page

- api/src/k8s_client.rs
- replicator/configuration/base.yaml
This PR:
* Adds missing `max_table_sync_workers` in dev config.
* Updates source postgres env var name for replicator.
> fix: update replicator config

- api/Cargo.toml
- api/src/config.rs
- api/src/main.rs
- api/src/startup.rs
- config/src/environment.rs
- config/src/load.rs
- telemetry/Cargo.toml
- telemetry/src/lib.rs
This PR adds Sentry to the API. In addition, it adds a new `staging` environment and slightly improves how environments are handled.
> feat(observability): Add Sentry in API

- .github/workflows/docker-build.yml
- .github/workflows/general.yml
- api/tests/common/test_app.rs
- config/src/environment.rs
- telemetry/src/lib.rs
This PR adds an action which is run when merging onto `main` a new PR.
> feat(ci): Add action for building docker images

- .github/workflows/audit.yml
- .github/workflows/ci.yml
- .github/workflows/docker-build.yml
This PR improves GitHub Actions by adding better caching, clearer step descriptions, job dependencies, and matrix execution.
> feat(ci): Improve GitHub Actions

- etl/src/v2/destination/bigquery.rs
- etl/src/v2/pipeline.rs
- etl/src/v2/replication/apply.rs
- etl/src/v2/replication/client.rs
- etl/src/v2/replication/table_sync.rs
- etl/src/v2/state/store/postgres.rs
- etl/src/v2/workers/apply.rs
- etl/src/v2/workers/table_sync.rs
- replicator/src/core.rs
- replicator/src/migrations.rs
This PR adds better logs for the replicator and etl crates.
> ref(logs): Improve logs

- Cargo.toml
- api/src/main.rs
- replicator/src/main.rs
This PR improves the Sentry integration in the following way:
- Uses the correct dependencies without disabling default features.
- Adds a top-level error handler.
- Adds panic handler.
- Correctly sets up sentry before the runtime (missed in the previous PR).
> fix(sentry): Improve Sentry integration

- etl/src/pipeline.rs
- etl/src/replication/apply.rs
- etl/src/replication/client.rs
- etl/src/replication/table_sync.rs
- etl/src/state/store/postgres.rs
- etl/src/workers/apply.rs
- etl/src/workers/table_sync.rs
This PR adds additional logs to the ETL code.
> feat(logs): Improve logs

- etl/benches/table_copies.rs
- scripts/benchmark.sh
- scripts/prepare_tpcc.sh
This PR updates the benchmark scripts to:
* Enable logging during benchmarking.
* Add the `order_line` table to the benchmarks.
> benchmark: update benchmark scripts

- api/src/routes/destinations.rs
- api/src/routes/destinations_pipelines.rs
- api/src/routes/images.rs
- api/src/routes/pipelines.rs
- api/src/routes/sources.rs
- api/src/routes/sources/publications.rs
- api/src/routes/sources/tables.rs
- api/src/routes/tenants.rs
- api/src/routes/tenants_sources.rs
- api/src/startup.rs
This PR uses the new nesting API in utoipa to make the declaration of nested routes more ergonomic.
> feat(openapi): Use nesting in utoipa

- Cargo.toml
- etl/src/workers/table_sync.rs
- etl/tests/failpoints/pipeline_test.rs
This PR implements the abort on panic in `etl`.
> ref(panics): Abort process on any panic

- api/src/routes/pipelines.rs
- api/tests/integration/pipelines_test.rs
- etl/src/workers/table_sync.rs
- postgres/src/replication/state.rs
This PR improves the table rollback endpoint by correctly checking the table replication state retry policy.
> feat(api): Improve endpoint for rollback

- etl-postgres/src/replication/schema.rs
This PR adds support for more types in the Postgres schema stored in the store.
> feat(store): Add more supported types in Postgres schema

- AGENTS.md
This PR adds an `AGENTS.md` file to be used with AI agents for working with ETL.
> feat(agents): Add AGENTS.md file

- etl-postgres/src/replication/db.rs
- etl-postgres/src/replication/schema.rs
- etl-postgres/src/replication/table_mappings.rs
This PR makes queries lowercase for `etl-postgres`.
> ref(sql): Make queries lowercase

- .github/workflows/ci.yml
This PR adds the CI run on main to make sure that the latest main has successful tests.
> feat(etl): Run CI on main

- README.md
This PR adds badges for CI and code coverage.
> feat(readme): Add badges

- etl-benchmarks/Cargo.toml
- etl-benchmarks/benches/table_copies.rs
- etl-benchmarks/scripts/mem_profile.sh
This PR adds a memory profiling script which allows to profile memory usage of the pipeline while running the benchmark.
> feat(profiling): Add script to perform memory profiling

- etl-api/src/k8s/base.rs
- etl-api/src/k8s/http.rs
- etl-api/src/k8s/mod.rs
- etl-api/src/lib.rs
- etl-api/src/routes/pipelines.rs
- etl-api/src/startup.rs
- etl-api/tests/support/k8s_client.rs
- etl-api/tests/support/test_app.rs
This PR improves the K8S implementation by restructuring it in the crate and also tuning resources based on the environment version.
> feat(k8s): Improve resource tuning of K8S
