supabase/etl

- pg_replicate/src/conversions/cdc_event.rs
Bug fix for boolean value parsing.
I did not create an issue beforehand, so I will describe the current behavior here. 
I am running PostgreSQL 17 (`PostgreSQL 17.0 (Debian 17.0-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit`). 
With the following table:
```sql
-- create a table
CREATE TABLE test(
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name TEXT NOT NULL,
archived BOOLEAN NOT NULL DEFAULT FALSE
);
-- add test data
INSERT INTO test (name, archived)
VALUES ('test row 1', true),
('test row 2', false);
```
I created the publication like so:
```sql
create publication my_publication for table test;
```
and later I ran the `stdout` example.
I ran the following query:
```sql
update test set name='test row 1' where id=1;
```
which resulted in …
> fix: boolean parsing

- pg_replicate/src/pipeline/mod.rs
Bug fix see #62 
`PipelineResumptionState` properties are made public
Right now visibility of properties of `PipelineResumptionState` is set to private. This prevents using `pg_replicate` as a library when using custom sinks
> fix: set pipeline resumption state props public

- pg_replicate/src/clients/postgres.rs
This PR fixes a syntax error. In earlier versions of pg, looks like a syntax error is thrown when using the `primary` keyword as an alias implicitly
Works when you explicitly put `as`:
> fix: syntax error when getting column schemas

- pg_replicate/src/clients/postgres.rs
In cases where a column name is used included in multiple indexes on a table, the join between pg_attribute and pg_index will return a row for each index involving that column. Fix here is to select distinct columns in order to avoid duplicate column names on table creation in the sink.
duplicate columns in sink table creation
select unique column names
N/A
> fix: retrieve distinct columns

- pg_replicate/src/pipeline/batching/data_pipeline.rs
- pg_replicate/src/pipeline/data_pipeline.rs
- pg_replicate/src/pipeline/mod.rs
- pg_replicate/src/pipeline/sinks/bigquery.rs
- pg_replicate/src/pipeline/sinks/duckdb/executor.rs
- pg_replicate/src/pipeline/sinks/duckdb/mod.rs
- pg_replicate/src/pipeline/sinks/duckdb/sink.rs
- pg_replicate/src/pipeline/sinks/mod.rs
- pg_replicate/src/pipeline/sinks/stdout.rs
- pg_replicate/src/pipeline/sources/mod.rs
- pg_replicate/src/pipeline/sources/postgres.rs
Implementation of #29.
- `PipelineError` becomes generic: `PipelineError<SrcErr: SourceError, SnkErr: SinkError>`
- We introduce the `SourceError` and `SinkError` marker traits which the respective errors must implement. This is a slight workaround because `PipelineError<SrcErr: Error, SnkErr: Error>` doesn't work (I tried, the type system doesn't like it), but it doesn't harm ergonomics too much.
- We add associated `Error` types on the `Sink`, `BatchSink`, and `Source` traits, with bounds on the respective `SinkError` and `SourceError` traits.
- We add a `CommonSourceError` type which encodes the common error variants implemented in the pipeline/source glue code, rather than the ones defined by the individual source/sink types.
- For convenience we add two never types: …
> Make sinks, sources, and pipelines generic on their errors

- pg_replicate/src/clients/postgres.rs
- pg_replicate/src/pipeline/sources/postgres.rs
Feature
#83
We read from `pg_publication_rel` to figure out the subset of columns that _are_ published.
This is done by adding a `publication: Option<&str>` argument to the `get_column_schemas` method and its callers, up to `PostgresSource::new`, and then using that when present. I've managed to do the work preserving a single query, though that did make it a bit gnarly to support both subsetted tables and full tables.
> Support publication column lists

- api/src/routes/tenants.rs
- api/tests/api/tenants.rs
The delete tenant API will now return ok even when a tenant doesn't exist. This makes the API idempotent and the client code in worker doesn't have to ignore 404s.
> delete tenant API always returns ok

- api/src/routes/images.rs
- api/src/routes/pipelines.rs
- api/src/routes/sinks.rs
- api/src/routes/sources.rs
- api/src/routes/sources/publications.rs
- api/src/routes/sources/tables.rs
- api/src/routes/tenants.rs
- api/tests/api/images.rs
- api/tests/api/pipelines.rs
- api/tests/api/sinks.rs
- api/tests/api/sources.rs
- api/tests/api/tenants.rs
- api/tests/api/test_app.rs
This is done to make it easy for the API to evolve in the future because it is easy to add another member to an object as opposed to an array whose structure is more rigid.
> API responses now always return objects and never arrays

- api/src/configuration.rs
- api/src/k8s_client.rs
- replicator/configuration/dev.yaml
- replicator/src/configuration.rs
- replicator/src/main.rs
After the recent changes in renaming the configuration to snake_case, deserializing the settings from environment variables was failing. This PR renames the environment variables to align with snake_case renaming.
> fix config in replicator

- deny.toml
This PR will fix the [failing security audit workflow](https://github.com/supabase/pg_replicate/actions/runs/13467313041/job/37635630241). The advisory can be removed from because pg_replicate's dependency tree no longer contains `yaml-rust` crate, which this advisory was about.
> removing a stale suppressed advisory

- api/src/db/sinks.rs
- api/src/replicator_config.rs
- api/src/routes/pipelines.rs
- api/tests/api/sinks.rs
- pg_replicate/examples/bigquery.rs
- pg_replicate/src/clients/bigquery.rs
- pg_replicate/src/pipeline/sinks/bigquery.rs
- replicator/src/configuration.rs
- replicator/src/main.rs
Adds support to configure the [max_staleness option](https://cloud.google.com/bigquery/docs/change-data-capture#create-max-staleness) for bigquery. Closes #51
> Configurable max staleness

- api/Dockerfile
- replicator/Dockerfile
Fix for failing docker builds: https://github.com/supabase/pg_replicate/actions/runs/13673977582/job/38230257153
> bump rustc version in dockerfiles to 1.85

- deny.toml
Suppresses Rust advisories about unmaintained crates. These are not actual vulnerabilities but just nudges for people to move to maintained alternatives. This helps keep the [security audit runs](https://github.com/supabase/pg_replicate/actions/runs/13731512274/job/38409320161) green.
> Suppress some aggressive Rust security advisories

- pg_replicate/src/conversions/cdc_event.rs
- pg_replicate/src/pipeline/sinks/bigquery.rs
- pg_replicate/src/pipeline/sinks/duckdb/executor.rs
This PR adds support for the `origin` and `truncate` replication message types in `cdc_event` conversion code. The bigquery and duckdb sinks for now just ignore these but will be enhanced in separate PRs to handle them.
Fixes #99
> add support for origin and truncate message types

- .vscode/settings.json
For a better IDE experience in VSCode, this PR changes the `rust-analyzer.cargo.features` setting to `all` which passes the `--all-features` flag to cargo for any cargo command run by the IDE (e.g. cargo clippy). This prevents `cargo clippy` warnings from appearing in those projects which did not have the `duckdb`, `bigquery` or `stdout` features enabled (e.g. the `replicator` project). To reproduce the warnings, with the old setting, open a file in the `replicator` project and save it and observe the rust-analyzer in the status bar turn yellow. To view that the fix works, do the same with the new setting.
> pass --all-features to cargo clippy

- .github/workflows/audit.yml
- .github/workflows/general.yml
Nothing vulnerable, just tightening up the default permissions allowed for GITHUB_TOKEN
> ci: explicit permission in GH actions

- pg_replicate/src/clients/postgres.rs
`pg_replicate` terminated with an error if the publication name contained capital letters.
In the `START_REPLICATION` command, `pg_replicate` was treating the publication name as a literal. It should have been treated as an identifier.
This is what the [Postgres docs](https://www.postgresql.org/docs/current/protocol-logical-replication.html#PROTOCOL-LOGICAL-REPLICATION-PARAMS) say on the format of the `publication_names` option for the `START_REPLICATION` command: 
> Comma separated list of publication names for which to subscribe (receive changes). The individual publication names are treated as standard objects names and can be quoted the same as needed. At least one publication name is required.
This means the correct format for `publication_names` is `... "publication_names" …
> fix incorrect syntax in start_replication command

- api/Cargo.toml
- api/src/main.rs
- api/src/startup.rs
- api/tests/api/database.rs
Running `cargo test` generates a lot of test databases for the api crate's end-to-end tests. These databases would accumulate after a lot of test runs and had to be cleaned up. To delete those databases we had a test which was marked ignored. If someone wanted to delete test databases, they'd comment out the `[ignore]` attribute and run `cargo run delete_test_databases`. Now we've moved the code to delete test databases as a command for the api crate. Now to delete the test databases, you'd run `cargo run -- delete-test-databasses` from the api folder. No more commenting out the `[ignore]` attribute.
> move the code to delete test database into a command from a test

- api/src/db/mod.rs
- api/src/db/sources.rs
- api/src/db/tenants.rs
- api/src/db/tenants_sources.rs
- api/src/routes/mod.rs
- api/src/routes/sources.rs
- api/src/routes/tenants.rs
- api/src/routes/tenants_sources.rs
- api/src/startup.rs
- api/tests/api/main.rs
- api/tests/api/sources.rs
- api/tests/api/tenants_sources.rs
- api/tests/api/test_app.rs
This PR adds a new endpoint to create a tenant and source in a single transaction. This is needed because currently these two are created by two separate API calls to `POST /tenants` and `POST /sources` when the Enable replication button is clicked in the studio UI. The separate API calls are prone to partial failure (the first API call succeeds while the second fails), recovering from which is not easy. This new API endpoint will be used to fix that partial failure.
> add the POST /tenants-sources endpoint

- api/src/db/mod.rs
- api/src/db/pipelines.rs
- api/src/db/sinks.rs
- api/src/db/sinks_pipelines.rs
- api/src/routes/mod.rs
- api/src/routes/pipelines.rs
- api/src/routes/sinks.rs
- api/src/routes/sinks_pipelines.rs
- api/src/startup.rs
- api/tests/api/main.rs
- api/tests/api/pipelines.rs
- api/tests/api/sinks.rs
- api/tests/api/sinks_pipelines.rs
- api/tests/api/test_app.rs
This PR adds a new endpoint to create a sink and pipeline in a single transaction. This is needed because currently these two are created by two separate API calls to POST /sinks and POST /pipelines when the Create destination button is clicked in the studio UI. The separate API calls are prone to partial failure (the first API call succeeds while the second fails), recovering from which is not easy. This new API endpoint will be used to fix that partial failure.
> add the POST /sinks-pipelines endpoint

- api/configuration/base.yaml
- api/src/configuration.rs
The worker settings were from when we had a background worker running in the API. Forgot to remove this code when the background worker was removed.
> remove unused code

- api/src/db/pipelines.rs
- api/src/db/sinks.rs
- api/src/db/sinks_pipelines.rs
- api/src/routes/pipelines.rs
- api/src/routes/sinks_pipelines.rs
- api/src/startup.rs
- api/tests/api/pipelines.rs
- api/tests/api/sinks.rs
- api/tests/api/sinks_pipelines.rs
- api/tests/api/test_app.rs
The new `POST /sinks-pipelines/{sink_id}/{pipeline_id}` endpoint allows a sink and a pipeline to be updated atomically in a transaction.
> add `POST /sinks-pipelines/{sink_id}/{pipeline_id}` endpoint

- api/migrations/20250506035802_cascade_delete_pipelines.sql
- api/tests/api/pipelines.rs
This PR enables cascade delete on foreign keys from `pipelines` tables to `sources` and `sinks` table to avoid making two separate calls when deleting a destination from the UI.
> Cascade delete pipelines

- Cargo.toml
- api/Cargo.toml
- api/src/configuration.rs
- api/src/lib.rs
- api/src/main.rs
- api/src/telemetry.rs
- replicator/Cargo.toml
- replicator/src/configuration.rs
- replicator/src/main.rs
- telemetry/Cargo.toml
- telemetry/src/lib.rs
In a dev environment:
* Logs are printed on stdout
* Logs are pretty printed with colors enabled
In a prod environment:
* Logs are sent to a file in the logs folder
* Writing to the file is done on a background process for performance
* Logs are written in structured json format
* Logs are rotated daily to avoid filling up the disk
* Maximum 5 log files are kept, older are rotated out
Some multi-line logs lines have been flattened into a single file as they didn't play well with the json output. The older bunyan format logger has been removed. Telemetry related code has been factored out into its own separate crate named `telemetry` and reused from both the `api` and the `replicator` crates. We are also now emitting more structured fields wherever possible. E.g. database details are …
> Improve logging in the API and replicator crates

- api/src/main.rs
- api/src/replicator_config.rs
- api/src/routes/pipelines.rs
- pg_replicate/src/pipeline/sinks/bigquery.rs
- replicator/configuration/base.yaml
- replicator/src/configuration.rs
- replicator/src/main.rs
- telemetry/src/lib.rs
This PR emits a field named `project` in the replicator's root span called `replication`. The `project` field can be used to filter for a specific project in logflare logs.
It also emits a log on span close only for the `api` crate and disables it for the `replicator` crate. Emitting on close for the `api` crate is required to log on request close. This is a bit of a hack but works for now. In future we'd like the tracing middleware to emit these logs because currently the middleware doesn't support it.
> emit project field in the root span in replicator

- api/src/k8s_client.rs
This PR adds a vector sidecar to replicator pods for sending logs to Logflare. There's also some renaming of existing k8s objects to make it clearer which container (replicator or vector) refers to which objects.
> feat: add vector sidecar to replicator pods

- api/src/k8s_client.rs
Forgot to enable and map the logs volume to the replicator and the vector sidecar containers in the last PR.
> enable logs volume in replicator and vector sidecar containers

- .github/workflows/general.yml
- scripts/init_db.sh
Without this the tests failed with the following error:
```
thread 'integration::replication_test::test_table_schema_copy_across_multiple_connections' panicked at etl/tests/integration/replication_test.rs:228:10:
called `Result::unwrap()` on an `Err` value: Client(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E53400), message: "all replication slots are in use", detail: None, hint: Some("Free one or increase max_replication_slots."), position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("slot.c"), line: Some(291), routine: Some("ReplicationSlotCreate") }) })
```
> fix: bump max_replication_slots to 100 to make tests pass

- etl/src/v2/conversions/event.rs
- etl/src/v2/destination/base.rs
- etl/src/v2/destination/memory.rs
- etl/src/v2/replication/apply.rs
- etl/src/v2/replication/client.rs
- etl/src/v2/replication/table_sync.rs
- etl/src/v2/schema/cache.rs
- etl/src/v2/state/store/memory.rs
- etl/src/v2/state/store/postgres.rs
- etl/src/v2/workers/apply.rs
- etl/src/v2/workers/base.rs
- etl/src/v2/workers/pool.rs
- etl/src/v2/workers/table_sync.rs
- etl/tests/common/destination_v2.rs
- etl/tests/common/event.rs
- etl/tests/common/state_store.rs
- etl/tests/integration/pipeline_v2_test.rs
- postgres/src/schema.rs
- postgres/src/tokio/test_utils.rs
This PR:
* Uses the type alias `TableId` everywhere an `Oid` was used to refer to a table id.
* Renames the `Hook` structs to `ApplyWorkerHook` and `TableSyncWorkerHook` respectively to make them easier to distinguish.
> refactor: use TableId instead of Oid and rename a couple of structs

- api/src/routes/destinations.rs
- api/src/routes/sources.rs
- api/tests/integration/snapshots/r#mod__integration__destination_test__all_destinations_can_be_read-2.snap
- api/tests/integration/snapshots/r#mod__integration__destination_test__all_destinations_can_be_read.snap
- api/tests/integration/snapshots/r#mod__integration__destination_test__an_existing_destination_can_be_read.snap
- api/tests/integration/snapshots/r#mod__integration__destination_test__an_existing_destination_can_be_updated.snap
- api/tests/integration/snapshots/r#mod__integration__destinations_pipelines_test__an_existing_destination_and_pipeline_can_be_updated.snap
- api/tests/integration/snapshots/r#mod__integration__destinations_pipelines_test__destination_and_pipeline_can_be_created.snap
- api/tests/integration/snapshots/r#mod__integration__sources_test__all_sources_can_be_read-2.snap
- api/tests/integration/snapshots/r#mod__integration__sources_test__all_sources_can_be_read.snap
- api/tests/integration/snapshots/r#mod__integration__sources_test__an_existing_source_can_be_read.snap
- api/tests/integration/snapshots/r#mod__integration__sources_test__an_existing_source_can_be_updated.snap
- api/tests/integration/snapshots/r#mod__integration__tenants_sources_test__tenant_and_source_can_be_created.snap
This PR strips away sensitive fields when returning data from responses.
> feat(api): Do not return sensitive fields in responses

- etl/src/v2/workers/apply.rs
This PR fixes the problem where in a fully static database with no transactions occurring, the table sync workers kept launching and exiting. The reasons are mentioned in detail in the related [issue](https://linear.app/supabase/issue/ETL-150/new-table-sync-workers-keep-launching) but in short, tables in sync done state are launched by the `process_syncing_tables` function which is called periodically. The fix is to not launch table sync workers in the sync done state (because they will exit anyway).
> fix: avoid unnecessary table sync worker launches

- etl/src/v2/replication/client.rs
- etl/tests/integration/replication_test.rs
This PR:
* Removes the `PgReplicationClient::duplicate` method to simplify the interface because the `PgReplicationClient::connect` method is enough. If someone wants to create two connections with the same config they can call the `PgReplicationClient::connect` method again with the same config.
* Removes the `pg_connection_config` and `with_tls` members from `PgReplicationClient`. This was made possible because of removing the `PgReplicationClient::duplicate` method.
> feat: remove duplicate method and simplify replication client

- etl/src/v2/workers/apply.rs
- etl/src/v2/workers/table_sync.rs
The `process_syncing_tables` function always returned `Ok(false)` when a table was in catch up phase, whether or not it had caught up with the catch up lsn value. This caused the table's catch up apply loop to end earlier than required.
> fix: process_syncing_tables returned a wrong value

- api/src/routes/destinations.rs
- api/tests/integration/snapshots/r#mod__integration__destination_test__all_destinations_can_be_read-2.snap
- api/tests/integration/snapshots/r#mod__integration__destination_test__all_destinations_can_be_read.snap
- api/tests/integration/snapshots/r#mod__integration__destination_test__an_existing_destination_can_be_read.snap
- api/tests/integration/snapshots/r#mod__integration__destination_test__an_existing_destination_can_be_updated.snap
- api/tests/integration/snapshots/r#mod__integration__destinations_pipelines_test__an_existing_destination_and_pipeline_can_be_updated.snap
- api/tests/integration/snapshots/r#mod__integration__destinations_pipelines_test__destination_and_pipeline_can_be_created.snap
This PR returns the non-stripped config for the destination. We are backtracking on our decision since right now not sending the key overcomplicates a lot of downstream code.
> feat(api): Do not return the stripped destination config

- telemetry/src/lib.rs
After the recent change to default the environment to prod, setting `ENABLE_TRACING` stopped working. This PR fixes this by setting the environment in tests to dev if `ENABLE_TRACING` is set.
> fix: setting `ENABLE_TRACING` did not work

- replicator/src/main.rs
This PR logs a replicator error alongside sending it to Sentry.
> feat(observability): Log top-level error

- api/Dockerfile
- replicator/Dockerfile
We use [let chains](https://blog.rust-lang.org/2025/06/26/Rust-1.88.0/) in the code which needs Rust version 1.88 to compile. This PR bumps the Rust version in dockerfiles to 1.88 to fix docker builds.
> bump rust version to 1.88 in dockerfiles

- api/src/k8s_client.rs
- api/src/main.rs
- etl/src/replication/apply.rs
- etl/src/replication/client.rs
- etl/src/replication/stream.rs
- etl/src/workers/table_sync.rs
- replicator/src/core.rs
- replicator/src/main.rs
This PR runs vector as a sidecar container so that it starts and stops before and after the main containers.
In addition, it adds more logs around the code.
> feat(k8s): Run vector as sidecar container

- etl/src/pipeline.rs
- etl/src/workers/apply.rs
- etl/tests/common/test_schema.rs
- etl/tests/integration/pipeline_test.rs
This PR improves the apply worker by changing how locking is performed while starting table sync workers and checking their state. In addition, it adds a new integration test for batching and renames all integration tests following Rust's best practices for naming tests.
> fix(core): Improve edge cases of replication

- etl/src/concurrency/mod.rs
- etl/src/concurrency/shutdown.rs
- etl/src/concurrency/signal.rs
- etl/src/concurrency/stream.rs
- etl/src/replication/apply.rs
- etl/src/replication/table_sync.rs
- etl/src/workers/apply.rs
- etl/src/workers/table_sync.rs
- etl/tests/integration/pipeline_test.rs
This PR improves the syncing algorithm for tables by making it reactive instead of time-based, resulting in a performance improvement in the time it takes for a table to transition from copying data to syncing data.
A clear outcome of this implementation is that our tests now run much more quickly. However, some tests had to be removed because certain behaviors became more difficult to test, as the advancement of phases is now driven not only by the apply worker’s incoming traffic but also by the table sync worker (e.g., the worker goes from `SyncWait` to `SyncDone` nearly instantly even if no events are coming in the apply worker).
> feat(pipeline): Improve performance of the pipeline

- etl/src/destination/bigquery.rs
The commit and start lsn values were swapped in the expected test output.
> fix a failing test

- api/src/routes/pipelines.rs
- api/tests/integration/pipelines_test.rs
This PR returns the table id from the replication status endpoint.
> feat(api): Return also table id from the status endpoint

- api/src/routes/pipelines.rs
- etl/benches/table_copies.rs
- etl/src/conversions/event.rs
- etl/src/destination/bigquery.rs
- etl/src/replication/apply.rs
- etl/src/replication/slot.rs
- etl/src/state/store/postgres.rs
- etl/src/test_utils/test_schema.rs
- etl/src/workers/table_sync.rs
- postgres/Cargo.toml
- postgres/src/replication/db.rs
- postgres/src/replication/state.rs
- postgres/src/schema.rs
This PR implements a new type for `TableId` to improve the types that we use within `ETL`. This replaces type aliases which are a weak way to express types.
> feat(postgres): Add new type for TableId

- config/src/shared/connection.rs
This PR implements sane defaults for the Postgres connection to avoid having the database misconfigured.
> feat(postgres): Add sane defaults for the connection

- api/src/routes/pipelines.rs
- etl/benches/table_copies.rs
- etl/src/destination/bigquery.rs
- etl/src/pipeline.rs
- etl/src/replication/apply.rs
- etl/src/replication/table_sync.rs
- etl/src/test_utils/test_schema.rs
- etl/src/workers/apply.rs
This PR uses `#[expect(clippy...)]` instead of `#[allow(clippy...)]` because when the code on which the attribute is applies is changed such that the lint is no longer needed, `expect` raises a warning `this lint expectation is unfulfilled`. This allows the developer to notice unnecessary suppressions of clippy lints and remove them.
Also removed some dead code.
> chore: use expect instead of allow

- api/src/routes/pipelines.rs
- api/src/startup.rs
- api/tests/common/test_app.rs
- api/tests/integration/pipelines_test.rs
- etl/src/state/store/postgres.rs
- postgres/src/replication/state.rs
This PR adds a new endpoint for rolling back the state which accepts a table id and a rollback type and rolls it back based on the rollback type. In addition, it improves the pipelines tests by generalizing lots of duplicated code to make tests less verbose.
> feat(api): Add new endpoint for rolling back the state

- etl-api/src/k8s_client.rs
- etl-api/src/routes/pipelines.rs
- etl-api/tests/common/k8s_client.rs
This PR removes a lot of the code which was returning pod error details. This is not needed anymore since we are opting to expose errors via logs directly.
> ref(api): Do not return detailed pod error stats

- etl-destinations/src/bigquery/core.rs
This PR implements an escaping strategy for the `BigQuery` destination which avoids the introduction of ambiguity when the table schema and table names in Postgres were using the same `_` delimiter used to create tables in `BigQuery`.
The escaping strategy is implemented and explained in detail in the code.
> feat(bigquery): Escape table names in BigQuery destination

- etl-api/Cargo.toml
The Dockerfile expected the binary generated by the `etl-api` to be named `etl-api` but it was actually named `api` thus failing the build. This PR renamed the binary to fix this problem.
> fix: update api binary name to etl-api

- etl-api/.sqlx/query-32d4ef8790cd672f7ad264113224bbf3cd8579f64afde9edec81f8580419f122.json
- etl-api/migrations/20250807150000_remove_cascade_delete_from_destinations_sources.sql
- etl-api/src/db/pipelines.rs
- etl-api/src/db/replicators.rs
- etl-api/src/routes/destinations_pipelines.rs
- etl-api/src/routes/pipelines.rs
- etl-api/src/startup.rs
- etl-api/tests/common/database.rs
- etl-api/tests/common/test_app.rs
- etl-api/tests/integration/destination_test.rs
- etl-api/tests/integration/destinations_pipelines_test.rs
- etl-api/tests/integration/pipelines_test.rs
- etl-api/tests/integration/sources_test.rs
This PR introduces a new endpoint that atomically deletes both a destination and its associated pipeline. It also includes the following improvements:
- Ensures that the replicator entry is deleted when its corresponding pipeline is removed. This is done assuming that there can be a single replicator bound per pipeline.
- Removes ON DELETE CASCADE constraints for sources and destinations. Instead, the system now explicitly throws an error if a source or destination with active pipelines is deleted. This makes deletion behavior more predictable and explicit.
> feat(api): Add new destinations pipelines delete endpoint and rework constraints

- docs/index.md
- etl-api/src/db/pipelines.rs
- etl-benchmarks/benches/table_copies.rs
- etl-destinations/src/bigquery/core.rs
- etl-destinations/tests/common/bigquery.rs
- etl-postgres/src/replication/mod.rs
- etl-postgres/src/replication/table_mappings.rs
- etl-replicator/migrations/20250812120000_create_table_mappings.sql
- etl/src/conversions/event.rs
- etl/src/destination/base.rs
- etl/src/destination/memory.rs
- etl/src/error.rs
- etl/src/failpoints.rs
- etl/src/pipeline.rs
- etl/src/replication/table_sync.rs
- etl/src/store/both/memory.rs
- etl/src/store/both/postgres.rs
- etl/src/store/schema/base.rs
- etl/src/test_utils/notify.rs
- etl/src/test_utils/test_destination_wrapper.rs
- etl/tests/failpoints/pipeline_test.rs
- etl/tests/integration/postgres_store.rs
This PR implements new table mappings in the state store with the goal of mapping the source table ID to the destination table ID. This is necessary because a pipeline might need to store the mapping between a specific source table ID and an internal table ID, and this mapping cannot be computed using only basic information such as the table ID and table schema/name.
In addition, it adds a new truncate table method, which is called to restore the table state if the data sync operation is interrupted.
> feat(store): Add new table mappings in the state store

- Cargo.toml
- etl-api/Cargo.toml
- etl-api/src/lib.rs
- etl-api/src/metrics.rs
- etl-api/src/routes/metrics.rs
- etl-api/src/routes/mod.rs
- etl-api/src/startup.rs
- etl-api/tests/integration/metrics_test.rs
- etl-api/tests/integration/mod.rs
This PR returns metrics from the api crate on the `/metrics` endpoint. These metrics will be scraped from this endpoint by victoria metrics. Following metrics are currently returned:
* `http_requests_total` (labels: endpoint, method, status): the total number of HTTP requests handled by the api.
* `http_requests_duration_seconds` (labels: endpoint, method, status): the request duration for all HTTP requests handled by the api.
More metrics will be added later.
> feat: add metrics to the api crate

- etl-config/src/shared/connection.rs
This PR removes `idle_in_transaction_session_timeout` since it's triggered on long table copies.
> feat(postgres): Change connection defaults

- etl-api/src/k8s_client.rs
This PR renames etl namespace:
* `replicator-data-plane` to `etl-data-plane`.
> refactor: rename etl namespaces

- etl-api/src/configs/destination.rs
- etl-api/src/configs/mod.rs
- etl-api/src/configs/pipeline.rs
- etl-api/src/configs/serde.rs
- etl-api/src/configs/source.rs
- etl-api/src/configs/store.rs
- etl-api/src/db/destinations_pipelines.rs
- etl-api/src/db/pipelines.rs
- etl-api/src/k8s_client.rs
- etl-api/src/routes/pipelines.rs
This PR fixes a bug for which we were storing the wrong config in the database, causing issue while deserializing.
This is a big problem which can be partially solved if we make sure via traits that we are only serializing and deserializing types that are `Storable`.
> fix(api): Implement storable trait to make it more reliable to store configs in the db

- etl-api/src/configs/destination.rs
- etl-api/src/configs/pipeline.rs
- etl-api/src/configs/source.rs
This PR skips serialization of `Option` fields to conform with the API specification.
> fix(api): Skip serializing option config

- etl-destinations/src/bigquery/core.rs
- etl/src/failpoints.rs
- etl/src/replication/table_sync.rs
- etl/tests/failpoints/pipeline_test.rs
This PR implements a fix for the BigQuery destination in which the system was throwing an error during truncation of a single table when a failure occurred during table copy but before the schema of a table was actually loaded.
> fix(bigquery): Allow missing table schema when truncate is issued

- etl-postgres/src/tokio/test_utils.rs
- etl/src/conversions/event.rs
- etl/src/pipeline.rs
- etl/src/replication/apply.rs
- etl/src/workers/apply.rs
- etl/src/workers/table_sync.rs
- etl/tests/integration/pipeline_test.rs
This PR fixes the handling of unknown tables by correctly ordering event conversion only after an event is confirmed to be processed. This doesn't apply to `Begin` and `Commit` events.
By reordering conversions, the apply loop doesn't crash anymore since it only handles tables that are present in the state and skips the others correctly. As a side effect, this PR also improves the performance of the pipeline since event conversion is now performed only when there is the guarantee that the event will be forwarded.
> fix(replication): Fix apply loop event conversion ordering

- etl/src/destination/base.rs
- etl/src/replication/table_sync.rs
This PR fixes a bug that was overlooked during the implementation of the rollback mechanism. Now, we can also go back in states, thus it could be that when in `Init` we also have to delete a slot and issue a truncate to the table. We unconditionally do this to simplify the implementation but technically we could avoid issuing the operation in certain cases (when the table has never been copied).
> fix(state): Reset slot and table also on Init

- etl-replicator/src/core.rs
- etl-replicator/src/main.rs
- etl-telemetry/src/tracing.rs
This PR adds the pipeline id to all the replicator logs as a top-level field.
> feat(logs): Add pipeline id to replicator logs

- etl-api/src/k8s_client.rs
This PR changes the labels on the replicator pods as follows:
* The `app` label is renamed to `app-name`. Now the `app-name` label will be used by the stateful set to mange the pod it owns.
* The `app` label will now have a value `etl-replicator-app` for all replicators. This label will be used by a `VMPodScrape` in https://github.com/supabase/etl-k8s/pull/87 to find out all the replicator pods from which to scrape metrics.
> feat: add same labels to all replicators

- etl-api/README.md
- etl-api/configuration/dev.yaml
- etl-api/src/authentication.rs
- etl-api/src/config.rs
- etl-api/src/startup.rs
- etl-api/tests/common/test_app.rs
- etl-api/tests/integration/mod.rs
- etl-config/src/load.rs
- etl-config/src/shared/connection.rs
- etl-config/src/shared/replicator.rs
This PR adds support for multiple api keys in ETL API to allow for key rotation.
> feat(auth): Add support for multiple api keys

- .github/workflows/docker-build.yml
- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
This PR changes the CI to open a PR before releasing a new version, this way the process requires manual approval after workflow start.
> ref(ci): Open a PR before releasing a new version

- etl-api/src/k8s_client.rs
Metrics are not being scraped from replicators because the metrics port was not exposed.
> fix: export metrics port from replicators

- etl-destinations/Cargo.toml
- etl-destinations/tests/support/bigquery.rs
- etl-destinations/tests/support/lakekeeper.rs
Fixes the partial CI/CD workflow, which has been broken due to an indirect dependency not being included. Solves it by including tokio as a dev dependency used across all the features.
Partial CI/CD workflow fails.
It doesn't fail.
Drive-by fix included of removing `futures` from the bigquery feature, as I noticed it wasn't getting used for anything (as I audited the dependencies via `cargo-udeps`.
> chore(ci): fix partial CI/CD

- etl-api/migrations/20250905100000_update_default_image_function.sql
This PR introduces a new database function that atomically sets an image as the default:
* If the image already exists, it is promoted to default.
* If it does not exist, a new record is created and marked as default.
To prevent race conditions, the function acquires a transaction-scoped advisory lock, ensuring that only one default-switch operation can run at a time.
The rationale for adopting a function is to make the update process flexible and usable from multiple places. Python scripts, PSQL, etc... This will be useful when we want to implement automatic image update via registry callbacks when new images are uploaded to a registry.
> feat(db): Add Postgres function to atomically update default image

- etl-api/src/k8s/http.rs
- etl-replicator/src/main.rs
This PR adds the version configuration in the replicator, this way we can have more details on which version is currently running when an error happens.
> feat(config): Add version configuration for the replicator

- etl-destinations/src/bigquery/encoding.rs
- etl-destinations/src/bigquery/validation.rs
- etl/src/types/cell.rs
Removed the following variants from enums:
* `ArrayCell::Null`
* `ArrayCellNonOptional::Null`
These were unnecessary because to represent a null array we can use `Cell::Null` and to represent a null element in the array we can use `Option::None` because all the `ArrayCell` variants contain data in the shape `Vec<Option<T>>`
> refactor: remove `ArrayCell::Null` and related variants

- etl-api/src/k8s/http.rs
- etl/src/replication/apply.rs
This PR increases the timeout to 5 minutes before K8S sends a `SIGKILL` to the replicator container.
> ref(k8s): Increase the timeout for the sigterm

- etl/src/replication/apply.rs
This PR improves the apply loop by avoiding the boxing of futures in the select.
> ref(apply): Avoid type erasing future on select

- README.md
- docs/index.md
- docs/tutorials/custom-implementations.md
- docs/tutorials/first-pipeline.md
- etl-api/src/configs/pipeline.rs
- etl-api/tests/pipelines.rs
- etl-api/tests/snapshots/destinations_pipelines__an_existing_destination_and_pipeline_can_be_updated-2.snap
- etl-api/tests/snapshots/destinations_pipelines__destination_and_pipeline_can_be_created-2.snap
- etl-api/tests/snapshots/pipelines__all_pipelines_can_be_read-2.snap
- etl-api/tests/snapshots/pipelines__all_pipelines_can_be_read.snap
- etl-api/tests/snapshots/pipelines__an_existing_pipeline_can_be_read.snap
- etl-api/tests/snapshots/pipelines__pipeline_config_can_be_updated-2.snap
- etl-api/tests/snapshots/pipelines__pipeline_config_can_be_updated-3.snap
- etl-api/tests/snapshots/pipelines__pipeline_config_can_be_updated-4.snap
- etl-api/tests/snapshots/pipelines__pipeline_config_can_be_updated.snap
- etl-api/tests/support/mocks.rs
- etl-benchmarks/benches/table_copies.rs
- etl-config/src/shared/base.rs
- etl-config/src/shared/pipeline.rs
- etl-destinations/tests/bigquery_pipeline.rs
- etl-examples/src/main.rs
- etl-replicator/configuration/base.yaml
- etl/src/lib.rs
- etl/src/state/table.rs
- etl/src/test_utils/notify.rs
- etl/src/test_utils/pipeline.rs
- etl/src/workers/table_sync.rs
- etl/tests/failpoints_pipeline.rs
- etl/tests/pipeline.rs
- etl/tests/replica_identity.rs
This PR adds a `max_attempts` mechanism to timed retires to avoid the worker continuing retrying errors indefinitely which could exhaust resources.
>  feat(retry): Add bounded retries across etl

- etl/src/replication/common.rs
- etl/src/state/table.rs
- etl/src/workers/apply.rs
This PR:
* Logs a warning in the logs when a table sync worker won't start because the table is in an error state. This helps debugging when running the replicator locally.
* Renames the method `get_table_replication_states` to `get_active_table_replication_states` and removes the `done` argument and simplifies it because it was always being called with `done` set to false.
> chore: improve logging when a table sync worker is in error

- etl-api/src/db/pipelines.rs
- etl-api/src/routes/pipelines.rs
- etl-api/tests/pipelines.rs
- etl-postgres/Cargo.toml
- etl-postgres/src/replication/lag.rs
- etl-postgres/src/replication/mod.rs
- etl-postgres/src/replication/slots.rs
- etl-postgres/src/replication/worker.rs
- etl/src/error.rs
- etl/src/replication/apply.rs
- etl/src/replication/stream.rs
- etl/src/replication/table_sync.rs
- etl/src/workers/apply.rs
- etl/src/workers/table_sync.rs
- etl/tests/pipeline.rs
This PR exposes replication lag metrics for the apply worker and table sync worker by fetching metrics from Postgres itself.
> feat(api): Expose replication lag metrics from source Postgres

- .github/workflows/ci.yml
Currently, whenever you push any commit to your branch, the old builds are still running and a new build is started. Once a new commit is added, the old test results no longer matter and it's just a waste of CI resources. Also reduces confusion with multiple builds running in parallel for the same branch/possibly blocking any merges.
With this little change, we ensure that whenever a new commit is added, the previous build is immediately canceled/stopped and only the build (latest commit) runs.
> build: automatically cancel old tests/build on new push

- etl-api/src/configs/destination.rs
- etl-api/tests/snapshots/destinations__an_existing_iceberg_supabase_destination_can_be_updated.snap
- etl-api/tests/snapshots/destinations_pipelines__an_existing_iceberg_supabase_destination_and_pipeline_can_be_updated.snap
- etl-api/tests/snapshots/destinations_pipelines__iceberg_supabase_destination_and_pipeline_can_be_created.snap
- etl-api/tests/support/mocks.rs
- etl-config/src/shared/destination.rs
- etl-replicator/src/core.rs
To be consistent with the UI whe s3 access key is shown as an obscured value because it is sensitive, etl api also now stores it as encrypted.
> feat: encrypt s3_access_key_id as well
